# =============================================================================
# Tests for the Sample application. See test.md for more information.
# =============================================================================

# Publish a message to the aisquick-sample topic via the Sample API in API Management
# @name publishMessage
POST https://{{apimHostname}}/aisquick-sample/messages
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
Ocp-Apim-Trace: true

{
    "message": "Hello, world!"
}


###


# Get the blob with the stored message from the aisquick-sample container
GET https://{{apimHostname}}/aisquick-sample/blobs/{{publishMessage.response.body.id}}
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
Ocp-Apim-Trace: true


###


# Get the table entity with the stored message from the aisquick-sample table
GET https://{{apimHostname}}/aisquick-sample/table-entities/{{publishMessage.response.body.id}}
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
Ocp-Apim-Trace: true 
