# =============================================================================
# Tests for the Sample application. See tests.md for more information.
# =============================================================================

# 1. Publish a message to the aisquick-sample topic on the Service Bus via the Sample API in API Management
# @name publishMessage
POST https://{{apimHostname}}/aisquick-sample/service-bus/messages
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
Ocp-Apim-Trace: true

{
    "message": "Hello, world!"
}


###


# 4a. Get the table entity with the stored message from the aisquick-sample table
GET https://{{apimHostname}}/aisquick-sample/table-entities/{{publishMessage.response.body.id}}
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
Ocp-Apim-Trace: true 


###


# 4b. Get the blob with the stored message from the aisquick-sample container
GET https://{{apimHostname}}/aisquick-sample/blobs/{{publishMessage.response.body.id}}
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
Ocp-Apim-Trace: true


###
